// Redux Turtles
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';


export const MARKETGAINERS_FETCHING = 'MARKETGAINERS_FETCHING';
export const MARKETGAINERS_SUCCESS = 'MARKETGAINERS_SUCCESS';
export const MARKETGAINERS_FAILURE = 'MARKETGAINERS_FAILURE';

export const EDITUSER_START = 'EDITUSER_START';
export const EDITUSER_SUCCESS = 'EDITUSER_SUCCESS';
export const EDITUSER_ERROR = 'EDITUSER_ERROR';


export const PROFILEPOST_START = 'PROFILEPOST_START';
export const PROFILEPOST_SUCCESS = 'PROFILEPOST_SUCCESS';
export const PROFILEPOST_ERROR = 'PROFILEPOST_ERROR';