// Redux Turtles
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const MARKETGAINERS_FETCHING = "MARKETGAINERS_FETCHING"
export const MARKETGAINERS_SUCCESS = "MARKETGAINERS_SUCCESS"
export const MARKETGAINERS_FAILURE = "MARKETGAINERS_FAILURE"